import { fireEvent, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { http, HttpResponse } from 'msw';
import { beforeEach, describe, expect, it } from 'vitest';
import { VentaServicios } from './VentaServicios';
import { api, choose, deferred, regressionSession, renderRoute } from '../../../components/test-support/regression';
import { server } from '../../../../tests/mocks/server';
import { activities, service, user } from '../../../../tests/fixtures/regression';
import { useAuthStore } from '../../../auth/authStore';
const prefix = 'venta.servicios.';
const permissions = [`${prefix}vista`, ...['ver', 'crear', 'editar', 'deshabilitar'].map(p => `${prefix}gestionar.${p}`)];
regressionSession(permissions);
let reads: number;
beforeEach(() => { reads = 0; server.use(http.get(`${api}/ventas/servicios`, () => { reads++; return HttpResponse.json([service()]); }), http.get(`${api}/tipos-actividad`, () => HttpResponse.json(activities))); });
async function mount() { renderRoute(<VentaServicios />); await screen.findByRole('row', { name: /Pack Prueba/ }); }
const expected = { nombre: 'Pack', descripcion: null, precioCentavos: 1235, vigenciaDias: 30, unitarioTexto: 'c/u', destacado: false, orden: 2, actividades: [{ tipoActividadId: 'a1', cantidadClases: 2 }, { tipoActividadId: 'a2', cantidadClases: 1 }] };
describe('VentaServicios: formularios y tabla local', () => {
    it.each([[], ['vista'], ['vista', 'gestionar.ver'], ['vista', 'gestionar.ver', 'gestionar.crear'], ['vista', 'gestionar.ver', 'gestionar.editar'], ['vista', 'gestionar.ver', 'gestionar.deshabilitar']].map(granted => [granted]))('permisos independientes %j', async (granted) => {
        useAuthStore.setState({ usuario: user({ permisos: granted.map(p => prefix + p) }) });
        renderRoute(<VentaServicios />);
        if (!granted.includes('vista') || !granted.includes('gestionar.ver')) {
            expect(screen.getByRole('alert').textContent).toContain('No tienes permiso');
            expect(screen.queryByRole('table')).toBeNull();
            return;
        }
        await screen.findByRole('row', { name: /Pack Prueba/ });
        expect(!!screen.queryByRole('button', { name: 'Nuevo paquete' })).toBe(granted.includes('gestionar.crear'));
        expect(!!screen.queryByRole('button', { name: 'Editar' })).toBe(granted.includes('gestionar.editar'));
        expect(!!screen.queryByRole('button', { name: 'Deshabilitar' })).toBe(granted.includes('gestionar.deshabilitar'));
    });
    it('clase suelta aplica vigencia7, nombre automático sólo vacío y precio redondeado exacto', async () => {
        const bodies: unknown[] = [];
        server.use(http.post(`${api}/ventas/servicios`, async ({ request }) => { bodies.push(await request.json()); return HttpResponse.json(service()); }));
        await mount();
        await userEvent.click(screen.getByRole('button', { name: 'Clase suelta' }));
        const dialog = screen.getByRole('dialog', { name: 'Nueva clase suelta' });
        expect((within(dialog).getByRole('spinbutton', { name: 'Vigencia (días)' }) as HTMLInputElement).value).toBe('7');
        expect((within(dialog).getByRole('spinbutton', { name: 'Orden' }) as HTMLInputElement).value).toBe('0');
        await choose('Actividad', 'Pilates');
        expect((within(dialog).getByRole('textbox', { name: 'Nombre' }) as HTMLInputElement).value).toBe('Clase de Pilates');
        fireEvent.change(within(dialog).getByRole('textbox', { name: 'Nombre' }), { target: { value: 'Clase propia' } });
        await choose('Actividad', 'Yoga');
        expect((within(dialog).getByRole('textbox', { name: 'Nombre' }) as HTMLInputElement).value).toBe('Clase propia');
        fireEvent.change(within(dialog).getByRole('spinbutton', { name: 'Precio (MXN)' }), { target: { value: '12.345' } });
        await userEvent.click(within(dialog).getByRole('button', { name: 'Guardar' }));
        await waitFor(() => expect(bodies).toEqual([{ nombre: 'Clase propia', descripcion: null, precioCentavos: 1235, vigenciaDias: 7, unitarioTexto: null, destacado: false, orden: 0, actividades: [{ tipoActividadId: 'a2', cantidadClases: 1 }] }]));
        await waitFor(() => expect(reads).toBe(2));
    });
    it('paquete mapea filas, excluye blanca y eliminación conserva otras; pending y POST exacto', async () => {
        const bodies: unknown[] = [];
        const hold = deferred<Response>();
        server.use(http.get(`${api}/ventas/servicios`, () => { reads++; return HttpResponse.json([service({ nombre: reads > 1 ? 'Pack listado' : 'Pack Prueba' })]); }), http.post(`${api}/ventas/servicios`, async ({ request }) => { bodies.push(await request.json()); return hold.promise; }));
        await mount();
        await userEvent.click(screen.getByRole('button', { name: 'Nuevo paquete' }));
        const dialog = screen.getByRole('dialog', { name: 'Nuevo paquete' });
        fireEvent.change(within(dialog).getByRole('textbox', { name: 'Nombre' }), { target: { value: '  Pack  ' } });
        fireEvent.change(within(dialog).getByRole('textbox', { name: 'Descripción' }), { target: { value: '  ' } });
        fireEvent.change(within(dialog).getByRole('spinbutton', { name: 'Precio (MXN)' }), { target: { value: '12.345' } });
        fireEvent.change(within(dialog).getByRole('textbox', { name: 'Texto unitario (opcional)' }), { target: { value: '  c/u ' } });
        fireEvent.change(within(dialog).getByRole('spinbutton', { name: 'Orden' }), { target: { value: '2' } });
        await choose('Actividad', 'Pilates');
        fireEvent.change(within(dialog).getByRole('spinbutton', { name: 'Clases' }), { target: { value: '2' } });
        await userEvent.click(within(dialog).getByRole('button', { name: 'Agregar actividad' }));
        await choose('Actividad', 'Yoga', 1);
        await userEvent.click(within(dialog).getByRole('button', { name: 'Agregar actividad' }));
        await choose('Actividad', 'Pilates', 2);
        // Unnamed delete icon: narrow row anchored by the labelled activity select.
        const row = within(dialog).getAllByRole('combobox', { name: 'Actividad' })[2].closest('.MuiFormControl-root')!.parentElement!;
        await userEvent.click(within(row).getByRole('button'));
        await userEvent.click(within(dialog).getByRole('button', { name: 'Agregar actividad' }));
        await userEvent.click(within(dialog).getByRole('button', { name: 'Guardar' }));
        await waitFor(() => expect(bodies).toEqual([expected]));
        expect((within(dialog).getByRole('button', { name: 'Guardando…' }) as HTMLButtonElement).disabled).toBe(true);
        hold.resolve(HttpResponse.json(service({ nombre: 'Pack servidor' })));
        await waitFor(() => expect(screen.queryByRole('dialog')).toBeNull());
        await waitFor(() => expect(reads).toBe(2));
        expect(await screen.findByRole('row', { name: /Pack listado/ })).toBeTruthy();
    });
    it('editar hidrata null, centavos, flags y actividades; PUT exacto conserva datos tras error y reintenta', async () => {
        const existing = service({ activo: false, destacado: true });
        const bodies: unknown[] = [];
        server.use(http.get(`${api}/ventas/servicios`, () => { reads++; return HttpResponse.json([existing]); }), http.put(`${api}/ventas/servicios/pA`, async ({ request }) => { bodies.push(await request.json()); return bodies.length === 1 ? HttpResponse.json({ message: 'Guardar falló' }, { status: 409 }) : HttpResponse.json(existing); }));
        await mount();
        await userEvent.click(screen.getByRole('button', { name: 'Editar' }));
        const dialog = screen.getByRole('dialog', { name: 'Editar paquete' });
        expect((within(dialog).getByRole('textbox', { name: 'Descripción' }) as HTMLInputElement).value).toBe('');
        expect((within(dialog).getByRole('spinbutton', { name: 'Precio (MXN)' }) as HTMLInputElement).value).toBe('123.45');
        expect((within(dialog).getByRole('switch', { name: 'Destacado' }) as HTMLInputElement).checked).toBe(true);
        expect((within(dialog).getByRole('switch', { name: 'Activo' }) as HTMLInputElement).checked).toBe(false);
        await userEvent.click(within(dialog).getByRole('button', { name: 'Guardar' }));
        await screen.findByText('Guardar falló');
        expect((within(dialog).getByRole('textbox', { name: 'Nombre' }) as HTMLInputElement).value).toBe('Pack Prueba');
        expect(reads).toBe(1);
        await userEvent.click(within(dialog).getByRole('button', { name: 'Guardar' }));
        await waitFor(() => expect(screen.queryByRole('dialog')).toBeNull());
        const { id: _id, creadoEn: _creadoEn, actividades, ...fields } = existing;
        const payload = { ...fields, actividades: actividades.map(({ tipoActividadId, cantidadClases }) => ({ tipoActividadId, cantidadClases })) };
        expect(bodies).toEqual([payload, payload]);
        await waitFor(() => expect(reads).toBe(2));
    });
    it.each([true, false])('activo=%s usa PATCH sin cuerpo y refresca respuesta visible', async (active) => {
        const bodies: (string | null)[] = [];
        let patched = false;
        server.use(http.get(`${api}/ventas/servicios`, () => { reads++; return HttpResponse.json([service({ activo: patched ? !active : active })]); }), http.patch(`${api}/ventas/servicios/pA/${active ? 'deshabilitar' : 'habilitar'}`, async ({ request }) => { bodies.push(await request.text()); patched = true; return new HttpResponse(null, { status: 204 }); }));
        await mount();
        await userEvent.click(screen.getByRole('button', { name: active ? 'Deshabilitar' : 'Habilitar' }));
        await waitFor(() => expect(reads).toBe(2));
        expect(bodies).toEqual(['']);
        expect(within(screen.getByRole('row', { name: /Pack Prueba/ })).getByText(active ? 'Inactivo' : 'Activo')).toBeTruthy();
    });
    it.each([['', '10', '30', 'El nombre es obligatorio'], ['Nombre', '0', '30', 'El precio debe ser mayor a 0'], ['Nombre', '10', '0', 'La vigencia debe ser mayor a 0 días'], ['Nombre', '10', '30', 'Agrega al menos una actividad']])('valida %s/%s/%s antes de escribir', async (name, price, days, message) => {
        await mount();
        await userEvent.click(screen.getByRole('button', { name: 'Nuevo paquete' }));
        const dialog = screen.getByRole('dialog', { name: 'Nuevo paquete' });
        fireEvent.change(within(dialog).getByRole('textbox', { name: 'Nombre' }), { target: { value: name } });
        fireEvent.change(within(dialog).getByRole('spinbutton', { name: 'Precio (MXN)' }), { target: { value: price } });
        fireEvent.change(within(dialog).getByRole('spinbutton', { name: 'Vigencia (días)' }), { target: { value: days } });
        await userEvent.click(within(dialog).getByRole('button', { name: 'Guardar' }));
        expect(screen.getByRole('alert').textContent).toBe(message);
        expect(reads).toBe(1);
    });
    it('clasifica, ordena y pagina localmente sin otra lectura', async () => {
        const data = Array.from({ length: 12 }, (_, i) => service({ id: `p${i}`, nombre: `Servicio ${String(i).padStart(2, '0')}`, precioCentavos: 100 * (12 - i), activo: i !== 0, actividades: i === 0 ? [{ tipoActividadId: 'a1', nombreActividad: 'Pilates', cantidadClases: 1 }] : i === 1 ? [...service().actividades, { tipoActividadId: 'a2', nombreActividad: 'Yoga', cantidadClases: 1 }] : service().actividades }));
        server.use(http.get(`${api}/ventas/servicios`, () => { reads++; return HttpResponse.json(data); }));
        renderRoute(<VentaServicios />);
        await screen.findByRole('row', { name: /Servicio 00/ });
        expect(screen.queryByRole('row', { name: /Servicio 10/ })).toBeNull();
        await userEvent.click(screen.getByRole('button', { name: /next page/i }));
        await screen.findByRole('row', { name: /Servicio 10/ });
        await choose('Filas por página', '25');
        expect(screen.getAllByRole('row')).toHaveLength(13);
        await userEvent.click(within(screen.getByRole('columnheader', { name: /Precio/ })).getByRole('button'));
        expect(screen.getAllByRole('row')[1].textContent).toContain('Servicio 11');
        await userEvent.click(within(screen.getByRole('columnheader', { name: /Precio/ })).getByRole('button'));
        expect(screen.getAllByRole('row')[1].textContent).toContain('Servicio 00');
        await userEvent.click(screen.getByRole('button', { name: /Clases/ }));
        expect(screen.getAllByRole('row')).toHaveLength(2);
        expect(screen.getByRole('row', { name: /Servicio 00/ }).textContent).toContain('Inactivo');
        await userEvent.click(screen.getByRole('button', { name: /Mixtos/ }));
        expect(screen.getByRole('row', { name: /Servicio 01/ })).toBeTruthy();
        expect(screen.queryByRole('row', { name: /Servicio 00/ })).toBeNull();
        expect(reads).toBe(1);
    });
    it.each([['Vigencia', 'A primero'], ['Estado', 'A primero'], ['Fecha', 'A primero']])('comparador local %s asc/desc sin GET extra', async (column, first) => {
        const a = service({ id: 'a', nombre: 'A primero', vigenciaDias: 7, activo: false, creadoEn: '2025-01-02T12:00:00Z' });
        const b = service({ id: 'b', nombre: 'B segundo', vigenciaDias: 30, activo: true, creadoEn: '2026-01-02T12:00:00Z' });
        server.use(http.get(`${api}/ventas/servicios`, () => { reads++; return HttpResponse.json([b, a]); }));
        renderRoute(<VentaServicios />);
        await screen.findByRole('row', { name: /A primero/ });
        const sort = within(screen.getByRole('columnheader', { name: new RegExp(`^${column}`) })).getByRole('button');
        await userEvent.click(sort);
        expect(screen.getAllByRole('row')[1].textContent).toContain(first);
        await userEvent.click(sort);
        expect(screen.getAllByRole('row')[1].textContent).toContain('B segundo');
        expect(reads).toBe(1);
    });
});
